name: Refresh Axway

on:
  workflow_call:
    inputs:
      deploy-environment:
        required: true
        type: string
      axway-frontend-path:
        required: true
        type: string
      swagger-url:
        required: true
        type: string
    secrets:
      axway-host:
        required: true
      axway-username:
        required: true
      axway-password:
        required: true

jobs:
  refresh:
    name: Refresh Axway
    runs-on: [self-hosted, windows, x64, msdeploy]
    environment: ${{ inputs.deploy-environment }}
    steps:
      - name: Run Refresh Axway Action
        uses: vermeer-corp/it-axway-automation@v1
        with:
          axway-username: ${{ secrets.axway-username }}
          axway-password: ${{ secrets.axway-password }}
          axway-host: ${{ secrets.axway-host }}
          api-deploy-config: false
          api-frontend-path: ${{ inputs.axway-frontend-path }}
          api-definition-path: ${{ inputs.swagger-url }}
